Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.<br><br>

Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

In [1]:
import numpy as np

In [3]:
n = 7                                       # setting an odd number

mat_zero = np.zeros((n, n), dtype=int)      # creating nxn zero matrix

x, y = mat_zero.shape                       # storing dimentions in x, y

# finding middle index of row and column
x_pos = x//2
y_pos = y//2

print(x_pos, y_pos)

3 3


In [4]:
for i in range(x):
    for j in range(y):
        if i == x_pos or j == y_pos:
            mat_zero[i, j] += 1

print(mat_zero)

[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]
