In [1]:
import numpy as np

## Creating an array of ones
*Syntax:* `np.ones(shape: tuple)`

`np.ones()` creates an array or matrix with all values as 1. This can be applicable when you want to instantiate a matrix before carrying out an operation on it.<br>
It takes a tuple as an argument where each value means rows, columns. If (n) is passed, it is considered as a column  i.e. (,n)<br>
default dtype of all values is float. However, it can be changed using the `dtype` kwarg.

**Tip**: Use `help()` method of numpy to see the syntax and the Docstring.

In [2]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [23]:
"""Creating a 1D array of 5 values with size 1, 5"""

arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [24]:
# Checking datatype
arr.dtype

dtype('float64')

^ *Notice that, by default, numpy creates data type = float64*

In [6]:
"""Creating a 1D array of 5 values with size 1, 5 and data type int"""

arr_int = np.ones(5, dtype=int)
arr_int

array([1, 1, 1, 1, 1])

In [8]:
# Checking datatype
arr_int.dtype

dtype('int32')

In [11]:
"""Creating a 2D array with size 5, 3 and data type int64"""

np.ones((5, 3), dtype='int64')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

## Creating a matrix of zeros
Syntax: `np.zeros(shape: tuple)`

In [12]:
"""Creating a 2D array with size 3, 3 and data type int32"""

np.zeros((3, 3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Creating an empty matrix
**Syntax:** ```np.empty(shape: tuple[int]) ``` <br><br>
Each value that gets displayed in an empty nparray is a random value and is not associated with the array itself.<br>
These type of arrays can be used to store the output of other matrix operations.

In [3]:
# creating an empty 3x3 matrix
np.empty((3, 3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.81810591e-321],
       [1.05700345e-307, 2.22523004e-307, 2.44031977e-312]])

## Creating an array of values over a range
Syntax: `np.arange(start:int, stop:int, step:int)`

np.arange takes a range of values as a tuple and generates an array. unlike np.ones() this generates an array with varying numeric values.<br>
The range is similar to Python's range() function. It takes start, end and step.

In [13]:
'''Creating an array with values rangign from 0 to 2'''

np.arange(3)

array([0, 1, 2])

In [28]:
'''Creating an array with values rangign from 0 to 3, while implicitly mentioning the dtype as float'''

np.arange(3.0)

array([0., 1., 2.])

In [15]:
'''Creating an array with values ranging from 3 to 34 with a step of 2'''

np.arange(3, 35, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

## Creating an array of random values 
Syntax: `np.random.randint(start:int, stop:int, size=int)`

This method takes argument as a range of valus expressed as a tuple.<br>
The size kwarg takes length of array.<br>
This method is based on the random python module.

In [16]:
'''Generating a 1D array of length 10 and an upperbound of 2(excluded) i.e. 0-1'''

np.random.randint(2, size=10)

array([1, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [29]:
'''Generating a 1D array of length 10 and an upperbound of 5(excluded) and lower 3 i.e. 3-4'''

np.random.randint(3, 5, size=10)

array([4, 3, 3, 4, 4, 4, 4, 3, 3, 4])

### Creatign 2D arrays using np.random.random()
Syntax: `np.random.random([n_rows:int, n_columns:int])`

In [30]:
'''Creating a 3x4 2D array. Default range for random is between 1 & 0'''

np.random.random([3, 4])

array([[0.58742167, 0.24836897, 0.08652025, 0.62946888],
       [0.5858029 , 0.62520467, 0.39095709, 0.43696896],
       [0.91219642, 0.51677399, 0.30245877, 0.99217396]])

### Linear space 
**syntax:** `np.linspace(start:int, stop:int, size:int)`

Linear space is used to generate an array between 2 start and stop values with length exactly as the third value.

In [31]:
"""Generates an array with length 20, values between 1 and 10. the difference between each value is constant"""

np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

**Q)** Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.<br>
Note: Make sure the array is of type int.

In [59]:
k = 4

arr = np.ones([k, k], dtype=int)

In [58]:
for i in range(1, len(arr)-1):
    for j in range(1, len(arr)-1):
        
        arr[i][j] = 0

arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

<h2 style = "color : Sky blue"> Exercises </h2>


Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range