## The learning objectives

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 

In [1]:
import numpy as np

In [3]:
array1 = np.array([10,20,30,40,50])
array2 = np.arange(5)                  # An array of length 5 starting from 0 till 4

In [4]:
'''Matrix addition'''

array1 + array2

array([10, 21, 32, 43, 54])

In [5]:
'''Matrix Multiplication'''

array1 * 2

array([ 20,  40,  60,  80, 100])

<h2 style = "color : Sky blue"> Stacking Arrays</h2> 

####  ```np.hstack()``` and ```np.vstack()```

Stacking is done using the ```np.hstack()``` and ```np.vstack()``` methods.<br>
For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.<br>


In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
z = np.array([6, 7, 4, 7, 8])

print(f'a: {a}')
print(f'b: {b}')
print(f'z: {z}')

a: [1 2 3]
b: [4 5 6]
z: [6 7 4 7 8]


#### ```np.hstack(list[nparrays])```
Note that the arrays must be passed inside of a list to avoid errors.<br>
In hstack we get a 1D array with a length that is the sum of length of all arrays that we pass.

In [26]:
print(f"hstacked a & b: {np.hstack([a, b])}")

hstacked a & b: [1 2 3 4 5 6]


In [27]:
# hstacking two arrays of unequal length.

np.hstack([a, z])

array([1, 2, 3, 6, 7, 4, 7, 8])

#### ```np.vstack(list[nparrays])```
In `np.vstack()` we get an NDarray with columns = the number of arrays we add.<br>
In `np.vstack ()`  the number of columns/values(length) in all matrices/arrays must be equal.

In [28]:
'''Vertically stacking a & b'''

np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
'''Trying to vstack two arrays with unequal length'''

np.vstack([z, a])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 3

In [30]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Reshaping arrays

`nparray.reshape(row:int, column:int)`<br>
The .`reshape()` method takes the number of rows and the number of columns and reshapes the array this method is applied to, to the shape that is passed in `.reshape()` as arguments.<br>
While passign arguments to `.reshape()` make sure that the product of the arguments is the size of the applied array.<br>
If you pass -1 to the argument, the matrix will be converted to a 1D array. However, the number of dimentions ultimatly depends on the number of arguments passed to `.reshape()`. Meaning that if you pass `1, -1` to `.reshape()` You will get a 2D array with just 1 row.

In [31]:
'''Generating an array of length 15'''

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
'''Reshaping the araay to a shape of 3, 5 i.e. 3 rows, 5 columns'''

np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
''' Trying to reshape the array to a shape of 3, 6 i.e. 3 rows, 6 columns'''

np.arange(15).reshape(3, 6)

ValueError: cannot reshape array of size 15 into shape (3,6)

### ```np.power(nparray, exponant[int]) and np.absolute(nparray)```

In [57]:
array1

array([10, 20, 30, 40, 50])

In [58]:
'''Raising alll values in array1 to the power of 3'''

np.power(array1, 3)

array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

In [60]:
x = np.array([-2, -1, 0, 1, 2])
x

array([-2, -1,  0,  1,  2])

In [62]:
'''Getting the absolute values of all values in x'''

np.absolute(x)

array([2, 1, 0, 1, 2])

## Trigonometric Functions

In [63]:
# pi is an inbuilt object in the numpy library that stores value of pi till 
np.pi

3.141592653589793

In [65]:
'''Creating an nparray'''

# theta is an nparray of 5 equally divided angles between 0 and pi
theta = np.linspace(0, np.pi, 5)
theta

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [66]:
'''Calculating the sinusoid of all values in theta.'''

np.sin(theta)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [68]:
'''Calculating the cosine of all values in theta.'''

np.cos(theta)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

In [69]:
'''Calculating the tangent of all values in theta.'''

np.tan(theta)

array([ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16, -1.00000000e+00,
       -1.22464680e-16])

## Exponential and Logarithmic functions

Natural Exponant $e = 2.71828182845904523536028747135266249775724709369995...$

In [104]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [105]:
'''Calculating natural exponant for each value in x'''

# This is e^x[0], e^x[0], ...e^x[x.size]
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [106]:
'''Calculating exponant for each value in x with e=2'''

np.exp2(x)

array([ 2.,  4.,  8., 16., 32.])

In [107]:
'''Calculating log base e for each value in x'''

np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [108]:
'''Calculating log base 2 for each value in x'''

np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [109]:
'''Calculating log base 10 for each value in x'''

np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [110]:
'''Calculating x[n]^4 for each value in x'''

np.power(x, 4)

array([  1,  16,  81, 256, 625], dtype=int32)

### ```np.multiply(nparray, multiplier[int|float], out=nparray)```

In [113]:
'''Creating an empty array of size 10'''

y = np.empty(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [114]:
'''Multiplying each value of x with 10 and storing in y'''

np.multiply(x, 10, out=y)

ValueError: operands could not be broadcast together with shapes (5,) () (10,) 

^ *here, we cannot store in y as output array is smaller than y.*

In [116]:
'''Multiplying each value of x with 10 and storing in every alternate y'''

np.multiply(x, 10, out=y[::2])

array([10., 20., 30., 40., 50.])

In [117]:
y

array([10.,  0., 20.,  0., 30.,  0., 40.,  0., 50.,  0.])

## Aggrigates

In [122]:
'''Creating a nparray'''

x2 = np.arange(1, 8)
x2

array([1, 2, 3, 4, 5, 6, 7])

In [129]:
'''Getting the arithmetic sum() of all values in x2'''
sum(x2)

28

In [127]:
'''Getting arithmetic sum using np.add.reduce(nparray) function'''

np.add.reduce(x2)

28

In [125]:
'''Getting the cumulative sum of all values in x2 using np.add.accumulate(nparray) function'''

np.add.accumulate(x2)

array([ 1,  3,  6, 10, 15, 21, 28])

In [128]:
'''Getting the cumulative product of all values in x2 using np.multiply.accumulate(nparray) function'''

np.multiply.accumulate(x2)

array([   1,    2,    6,   24,  120,  720, 5040])

## Basic Operations in Linear Algebra

NumPy provides the ```np.linalg``` package to apply common linear algebra operations, such as:
* ```np.linalg.inv```: Inverse of a matrix
* ```np.linalg.det```: Determinant of a matrix
* ```np.linalg.eig```: Eigenvalues and eigenvectors of a matrix
    
Also, you can multiple matrices using ```np.dot(a, b)```. 

In [130]:
'''Declaring a 2D ndarray'''

A = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

### Rank of a Matrix

In [131]:
np.linalg.matrix_rank(A)

3

### Trace of a Matrix

In [132]:
np.trace(A)

11

### Determinant of a Matrix

In [133]:
np.linalg.det(A)

-306.0

### Inverse of a Matrix

In [134]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [135]:
'''Storing the inverse in a variable'''

B = np.linalg.inv(A)

### Matrix multiplication

In [136]:
np.matmul(A, B) #actual matrix multiplication

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [-4.16333634e-17,  1.38777878e-16,  1.00000000e+00]])

In [137]:
A * B

array([[ 1.05882353, -0.00326797, -0.02287582],
       [ 0.23529412,  0.26143791,  0.4248366 ],
       [-0.23529412,  1.20261438,  0.36601307]])

### Exponanting a Matrix with Matrix

Here, we multiply a matrix to itself.

In [138]:
# matrix multiplication i.e. AxAxA
np.linalg.matrix_power(A, 3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])